## pro start configure
server:
  port: 8080

## database configure
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/[your database]?characterEncoding=utf8&serverTimezone=UTC
    username: [your username]
    password: [your password]
  application:
    name: redis
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0

## mqtt configure
mqtt:
  address: tcp://127.0.0.1:1883
  client_id: iot_sub
  user_name: your username
  password: your password
  subTopic: /topics/pub
  pubTopic: devPubTopics
  keep_alive: 60
  timeout: 60

## token
jwt:
  expire: 604800
  secret: "qYYjXt7s1C*nEC%9RCwQGFA$YwPr$Jrj"

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.edu.swjtu

images.path: /IotFronted/src/assets/images/

