## pro start configure
server:
  port: 8080

## database configure
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iott?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456

## mqtt configure
mqtt:
  address: tcp://127.0.0.1:1883
  client_id: iot_sub
  user_name: amdin
  password: yyx156457
  subTopic: /topics/led/pub
  pubTopic: devPubTopics
  keep_alive: 60
  timeout: 60

## token
jwt:
  expire: 604800
  secret: "qYYjXt7s1C*nEC%9RCwQGFA$YwPr$Jrj"

